-- Gymlic preset library seed data, ported verbatim from
-- supabase/migrations 0012 (exercises) and 0027 (foods).
-- Presets are the rows with created_by = NULL; every trainer sees them.
-- Safe to re-run: it clears the presets first, leaving custom entries alone.

SET NAMES utf8mb4;

DELETE FROM exercises WHERE created_by IS NULL;
INSERT INTO exercises (id, name, name_en, muscle_group) VALUES
  (UUID(), 'پرس سینه هالتر (نیمکت صاف)', 'Barbell Bench Press', 'سینه'),
  (UUID(), 'پرس سینه دمبل', 'Dumbbell Bench Press', 'سینه'),
  (UUID(), 'پرس بالا سینه هالتر', 'Incline Barbell Bench Press', 'سینه'),
  (UUID(), 'پرس بالا سینه دمبل', 'Incline Dumbbell Press', 'سینه'),
  (UUID(), 'شنا سوئدی', 'Push-Up', 'سینه'),
  (UUID(), 'قفسه سینه با دمبل', 'Dumbbell Fly', 'سینه'),
  (UUID(), 'کراس اُور سیم‌کش', 'Cable Crossover', 'سینه'),
  (UUID(), 'بارفیکس', 'Pull-Up', 'پشت'),
  (UUID(), 'زیر بغل سیم‌کش دست باز', 'Wide-Grip Lat Pulldown', 'پشت'),
  (UUID(), 'پارویی هالتر خم', 'Barbell Bent-Over Row', 'پشت'),
  (UUID(), 'پارویی دمبل تک‌خم', 'One-Arm Dumbbell Row', 'پشت'),
  (UUID(), 'ددلیفت', 'Deadlift', 'پشت'),
  (UUID(), 'پارویی سیم‌کش نشسته', 'Seated Cable Row', 'پشت'),
  (UUID(), 'شراگ با هالتر', 'Barbell Shrug', 'پشت'),
  (UUID(), 'اسکات با هالتر', 'Barbell Squat', 'پا'),
  (UUID(), 'پرس پا با دستگاه', 'Leg Press', 'پا'),
  (UUID(), 'لانگز با دمبل', 'Dumbbell Lunge', 'پا'),
  (UUID(), 'جلو پا با دستگاه', 'Leg Extension', 'پا'),
  (UUID(), 'پشت پا با دستگاه', 'Leg Curl', 'پا'),
  (UUID(), 'ددلیفت رومانیایی', 'Romanian Deadlift', 'پا'),
  (UUID(), 'هیپ تراست', 'Hip Thrust', 'پا'),
  (UUID(), 'ساق پا ایستاده', 'Standing Calf Raise', 'ساق پا'),
  (UUID(), 'ساق پا نشسته', 'Seated Calf Raise', 'ساق پا'),
  (UUID(), 'ساق پا با دستگاه اسمیت', 'Smith Machine Calf Raise', 'ساق پا'),
  (UUID(), 'پرس سرشانه هالتر', 'Barbell Overhead Press', 'شانه'),
  (UUID(), 'پرس سرشانه دمبل', 'Dumbbell Shoulder Press', 'شانه'),
  (UUID(), 'نشر جانب با دمبل', 'Dumbbell Lateral Raise', 'شانه'),
  (UUID(), 'نشر خم (دلتوئید خلفی)', 'Bent-Over Rear Delt Raise', 'شانه'),
  (UUID(), 'فیس پول', 'Face Pull', 'شانه'),
  (UUID(), 'نشر جلو با دمبل', 'Dumbbell Front Raise', 'شانه'),
  (UUID(), 'جلو بازو هالتر', 'Barbell Curl', 'جلو بازو'),
  (UUID(), 'جلو بازو دمبل', 'Dumbbell Curl', 'جلو بازو'),
  (UUID(), 'جلو بازو چکشی', 'Hammer Curl', 'جلو بازو'),
  (UUID(), 'جلو بازو لاری', 'Preacher Curl', 'جلو بازو'),
  (UUID(), 'جلو بازو سیم‌کش', 'Cable Curl', 'جلو بازو'),
  (UUID(), 'پشت بازو سیم‌کش میله صاف', 'Triceps Pushdown', 'پشت بازو'),
  (UUID(), 'پشت بازو هالتر خوابیده', 'Lying Triceps Extension (Skull Crusher)', 'پشت بازو'),
  (UUID(), 'دیپ روی موازی', 'Triceps Dip', 'پشت بازو'),
  (UUID(), 'پشت بازو دمبل تک‌خم', 'Dumbbell Kickback', 'پشت بازو'),
  (UUID(), 'پشت بازو فرانسوی', 'Overhead Triceps Extension', 'پشت بازو'),
  (UUID(), 'کرانچ', 'Crunch', 'شکم'),
  (UUID(), 'پلانک', 'Plank', 'شکم'),
  (UUID(), 'بالا آوردن پا آویزان', 'Hanging Leg Raise', 'شکم'),
  (UUID(), 'کرانچ سیم‌کش', 'Cable Crunch', 'شکم'),
  (UUID(), 'پیچ روسی', 'Russian Twist', 'شکم'),
  (UUID(), 'زیر شکم با دستگاه', 'Ab Machine Crunch', 'شکم'),
  (UUID(), 'دویدن', 'Running', 'کاردیو'),
  (UUID(), 'طناب زدن', 'Jump Rope', 'کاردیو'),
  (UUID(), 'دوچرخه ثابت', 'Stationary Bike', 'کاردیو'),
  (UUID(), 'الپتیکال', 'Elliptical Trainer', 'کاردیو');

DELETE FROM foods WHERE created_by IS NULL;
INSERT INTO foods (id, name, name_en, category, default_unit) VALUES
  (UUID(), 'سینه مرغ', 'Chicken Breast', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'ران مرغ بدون پوست', 'Skinless Chicken Thigh', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'گوشت گوساله کم‌چرب', 'Lean Beef', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'گوشت گوسفند کم‌چرب', 'Lean Lamb', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'ماهی قزل‌آلا', 'Trout', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'ماهی سالمون', 'Salmon', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'تن ماهی در آب', 'Canned Tuna in Water', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'میگو', 'Shrimp', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'تخم‌مرغ کامل', 'Whole Egg', 'منابع پروتئینی', 'عدد'),
  (UUID(), 'سفیده تخم‌مرغ', 'Egg White', 'منابع پروتئینی', 'عدد'),
  (UUID(), 'بوقلمون', 'Turkey Breast', 'منابع پروتئینی', 'گرم'),
  (UUID(), 'برنج سفید پخته', 'Cooked White Rice', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'برنج قهوه‌ای پخته', 'Cooked Brown Rice', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'جو دوسر (اُتمیل)', 'Rolled Oats', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'نان سنگک', 'Sangak Bread', 'کربوهیدرات و غلات', 'برش'),
  (UUID(), 'نان بربری', 'Barbari Bread', 'کربوهیدرات و غلات', 'برش'),
  (UUID(), 'نان جو', 'Barley Bread', 'کربوهیدرات و غلات', 'برش'),
  (UUID(), 'ماکارونی پخته', 'Cooked Pasta', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'سیب‌زمینی آب‌پز', 'Boiled Potato', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'سیب‌زمینی شیرین', 'Sweet Potato', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'کینوا پخته', 'Cooked Quinoa', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'ذرت پخته', 'Cooked Corn', 'کربوهیدرات و غلات', 'گرم'),
  (UUID(), 'عدس پخته', 'Cooked Lentils', 'حبوبات', 'گرم'),
  (UUID(), 'لپه پخته', 'Cooked Split Peas', 'حبوبات', 'گرم'),
  (UUID(), 'نخود پخته', 'Cooked Chickpeas', 'حبوبات', 'گرم'),
  (UUID(), 'لوبیا قرمز پخته', 'Cooked Red Beans', 'حبوبات', 'گرم'),
  (UUID(), 'لوبیا چیتی پخته', 'Cooked Pinto Beans', 'حبوبات', 'گرم'),
  (UUID(), 'سویا', 'Soy Chunks', 'حبوبات', 'گرم'),
  (UUID(), 'شیر کم‌چرب', 'Low-Fat Milk', 'لبنیات', 'لیوان'),
  (UUID(), 'ماست کم‌چرب', 'Low-Fat Yogurt', 'لبنیات', 'گرم'),
  (UUID(), 'ماست یونانی', 'Greek Yogurt', 'لبنیات', 'گرم'),
  (UUID(), 'پنیر کم‌چرب', 'Low-Fat Cheese', 'لبنیات', 'گرم'),
  (UUID(), 'کشک', 'Kashk', 'لبنیات', 'قاشق غذاخوری'),
  (UUID(), 'دوغ بدون گاز', 'Doogh', 'لبنیات', 'لیوان'),
  (UUID(), 'شیر سویا', 'Soy Milk', 'لبنیات', 'لیوان'),
  (UUID(), 'کاهو', 'Lettuce', 'سبزیجات', 'گرم'),
  (UUID(), 'گوجه‌فرنگی', 'Tomato', 'سبزیجات', 'عدد'),
  (UUID(), 'خیار', 'Cucumber', 'سبزیجات', 'عدد'),
  (UUID(), 'کلم بروکلی', 'Broccoli', 'سبزیجات', 'گرم'),
  (UUID(), 'اسفناج', 'Spinach', 'سبزیجات', 'گرم'),
  (UUID(), 'هویج', 'Carrot', 'سبزیجات', 'عدد'),
  (UUID(), 'کدو سبز', 'Zucchini', 'سبزیجات', 'گرم'),
  (UUID(), 'فلفل دلمه‌ای', 'Bell Pepper', 'سبزیجات', 'عدد'),
  (UUID(), 'پیاز', 'Onion', 'سبزیجات', 'عدد'),
  (UUID(), 'سبزی خوردن', 'Fresh Herbs', 'سبزیجات', 'مشت'),
  (UUID(), 'موز', 'Banana', 'میوه‌ها', 'عدد'),
  (UUID(), 'سیب', 'Apple', 'میوه‌ها', 'عدد'),
  (UUID(), 'پرتقال', 'Orange', 'میوه‌ها', 'عدد'),
  (UUID(), 'خرما', 'Date', 'میوه‌ها', 'عدد'),
  (UUID(), 'انگور', 'Grapes', 'میوه‌ها', 'گرم'),
  (UUID(), 'توت‌فرنگی', 'Strawberry', 'میوه‌ها', 'گرم'),
  (UUID(), 'کیوی', 'Kiwi', 'میوه‌ها', 'عدد'),
  (UUID(), 'هندوانه', 'Watermelon', 'میوه‌ها', 'گرم'),
  (UUID(), 'آناناس', 'Pineapple', 'میوه‌ها', 'گرم'),
  (UUID(), 'بادام', 'Almonds', 'چربی‌های سالم', 'گرم'),
  (UUID(), 'گردو', 'Walnuts', 'چربی‌های سالم', 'گرم'),
  (UUID(), 'پسته', 'Pistachios', 'چربی‌های سالم', 'گرم'),
  (UUID(), 'بادام‌زمینی', 'Peanuts', 'چربی‌های سالم', 'گرم'),
  (UUID(), 'کره بادام‌زمینی', 'Peanut Butter', 'چربی‌های سالم', 'قاشق غذاخوری'),
  (UUID(), 'روغن زیتون', 'Olive Oil', 'چربی‌های سالم', 'قاشق غذاخوری'),
  (UUID(), 'آووکادو', 'Avocado', 'چربی‌های سالم', 'عدد'),
  (UUID(), 'تخم چیا', 'Chia Seeds', 'چربی‌های سالم', 'قاشق غذاخوری'),
  (UUID(), 'تخمه کدو', 'Pumpkin Seeds', 'چربی‌های سالم', 'گرم'),
  (UUID(), 'پودر پروتئین وی', 'Whey Protein Powder', 'مکمل‌ها', 'اسکوپ'),
  (UUID(), 'کراتین مونوهیدرات', 'Creatine Monohydrate', 'مکمل‌ها', 'گرم'),
  (UUID(), 'گینر', 'Mass Gainer', 'مکمل‌ها', 'اسکوپ'),
  (UUID(), 'مولتی‌ویتامین', 'Multivitamin', 'مکمل‌ها', 'عدد'),
  (UUID(), 'امگا ۳', 'Omega-3', 'مکمل‌ها', 'عدد'),
  (UUID(), 'آب', 'Water', 'نوشیدنی‌ها', 'لیوان'),
  (UUID(), 'چای سبز', 'Green Tea', 'نوشیدنی‌ها', 'لیوان'),
  (UUID(), 'قهوه تلخ', 'Black Coffee', 'نوشیدنی‌ها', 'فنجان'),
  (UUID(), 'آب‌میوه طبیعی', 'Fresh Fruit Juice', 'نوشیدنی‌ها', 'لیوان');
